version: '3'

services:
 
  ngrok:
    container_name: ngrok
    restart: always
    build: .
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - ./core/ngrok_control.py:/usr/src/ngrok_api/ngrok_control.py
